### ISSUE TITLE
Any TODO list of simdota2?

### ISSUE THREAD

**Issue by lenLRX** [pydota2/pydota2#13]
the simdota2 is enough for my own usage now, I am not clear what to do.

**Comment by Nostrademous** [comment]
I will get back to you on this in 1-2 days with a series of issues. Currently away for the weekend.

One thing is to create actual damage calculation for unit vs unit using appropriate damage type (piercing vs normal vs siege).

Also, I feel we should rename the Sprite class to Unit to better mirror the game and allow easy to understand inheritance as we flash it out.

Finally, what I will need is a serialized world state dump function that I can send the output off to my code for RL that takes the expected form of Valve’s protobuf.

**Comment by lenLRX** [comment]
got it :)

**Comment by Nostrademous** [comment]
Created a Simulator project to track work on that.
